// `useStateEffect` forwards EVERY directional spacing / corner prop.
//
// WHY THIS FILE EXISTS, and why it is derived from the maps rather than
// from a hand-typed list of prop names.
//
// `useStateEffect` does not wrap `props`. It builds a `reactive({ get x ()
// {…} })` bag per axis and casts it `as IPaddingProps` / `as IMarginProps`
// / `as IRoundedProps` before handing it to the underlying composable. A
// getter bag exposes ONLY the keys it names, and the cast means TypeScript
// never notices a missing one — so a prop left out of the bag reads as
// fully implemented (declared on the interface, consumed by its composable,
// green type-check) while silently emitting NOTHING on every component
// routed through `useStateEffect`.
//
// That bug has already shipped three times in this exact file, by its own
// comments: border per-side, then `borderBlock` / `borderInline`, then the
// four physical `rounded{Corner}` props. Each time `useBorder` / `useRounded`
// were fixed and the curated getter list was not.
//
// Blast radius, measured on this commit rather than quoted — components that
// BOTH call `useStateEffect` and extend the interface, resolving `extends`
// transitively from `defineProps<I…>`:
//
//     IPaddingProps   30 / 33 components
//     IMarginProps    30 / 33
//     IRoundedProps   31 / 33
//
// So a single omitted getter is a dead prop on ~30 components.
//
// The defence: every expectation below is generated by iterating the MAPS in
// `consts/Commons/spacing.const.ts` — the same tables the composables
// iterate. Add a directional prop to a map and forget its getter here, and
// this spec goes red on its own, with the offending prop named. It cannot
// go stale the way a hand-written list does.
//
// ── On the measurement technique ───────────────────────────────────────
// Every assertion reads the DECLARATION STRINGS the composables push, never
// `getComputedStyle`. Under jsdom `getComputedStyle` never resolves a
// `var()` and returns a fabricated `16px` default instead (#398), which
// fakes both a pass and a failure. The values used here are plain literals
// (`'8px'`, `'12px'`), so the string assertions are exact and need no
// browser.

import { computed, defineComponent, h, reactive, ref } from 'vue'
import { mount } from '@vue/test-utils'
import { describe, expect, it } from 'vitest'

import {
    MARGIN_LOGICAL_AXIS_MAP,
    MARGIN_LOGICAL_SIDE_MAP,
    MARGIN_POSITION_MAP,
    PADDING_LOGICAL_AXIS_MAP,
    PADDING_LOGICAL_SIDE_MAP,
    PADDING_POSITION_MAP,
    ROUNDED_CORNER_MAP,
    ROUNDED_LOGICAL_CORNER_MAP
} from '@origam/consts/Commons/spacing.const'

import { useStateEffect } from '@origam/composables/Commons/stateEffect.composable'

/**
 * Mount a host that calls `useStateEffect` with `props`, and hand back its
 * API. `useStateEffect` reads `getCurrentInstanceName()` internally, so it
 * has to run inside a real component instance — not bare in the test body.
 */
function stateEffectApi (props: Record<string, unknown>) {
    let api!: ReturnType<typeof useStateEffect>

    mount(defineComponent({
        name: 'OrigamStateEffectHost',
        setup () {
            api = useStateEffect(reactive(props) as never)
            return () => h('div')
        }
    }))

    return api
}

// Every directional prop, paired with the CSS declaration prefix it must
// produce. Built from the maps, so the three grids (physical side, logical
// axis, logical side) are covered without naming a single prop by hand.
const PADDING_CASES: Array<[string, string]> = [
    ...PADDING_POSITION_MAP.map(({side, prop}) => [prop, `padding-${side}`] as [string, string]),
    ...PADDING_LOGICAL_AXIS_MAP.map(({axis, prop}) => [prop, `padding-${axis}`] as [string, string]),
    ...PADDING_LOGICAL_SIDE_MAP.map(({side, prop}) => [prop, `padding-${side}`] as [string, string]),
]

const MARGIN_CASES: Array<[string, string]> = [
    ...MARGIN_POSITION_MAP.map(({side, prop}) => [prop, `margin-${side}`] as [string, string]),
    ...MARGIN_LOGICAL_AXIS_MAP.map(({axis, prop}) => [prop, `margin-${axis}`] as [string, string]),
    ...MARGIN_LOGICAL_SIDE_MAP.map(({side, prop}) => [prop, `margin-${side}`] as [string, string]),
]

const ROUNDED_CASES: Array<[string, string]> = [
    ...ROUNDED_CORNER_MAP.map(({corner, prop}) => [prop, `border-${corner}-radius`] as [string, string]),
    ...ROUNDED_LOGICAL_CORNER_MAP.map(({corner, prop}) => [prop, `border-${corner}-radius`] as [string, string]),
]

// ───────────────────────────────────────────────────────────────────────
// 1. The forwarding itself — one test per prop, generated.
//    Two distinct values must produce two distinct outputs: asserting a
//    single value renders "something" would also pass against a hardcoded
//    constant, which is the failure mode that let the earlier omissions sit
//    unnoticed.
// ───────────────────────────────────────────────────────────────────────

describe('useStateEffect forwards every padding directional', () => {
    it('covers all three grids (guards against a map losing entries)', () => {
        // 4 physical sides + 2 logical axes + 4 logical sides
        expect(PADDING_CASES).toHaveLength(10)
    })

    it.each(PADDING_CASES)('%s reaches usePadding and emits %s', (prop, cssProp) => {
        const a = stateEffectApi({[prop]: '8px'}).paddingStyles.value
        const b = stateEffectApi({[prop]: '12px'}).paddingStyles.value

        expect(a).toContain(`${cssProp}: 8px`)
        expect(b).toContain(`${cssProp}: 12px`)
        expect(a).not.toEqual(b)
    })
})

describe('useStateEffect forwards every margin directional', () => {
    it('covers all three grids', () => {
        expect(MARGIN_CASES).toHaveLength(10)
    })

    it.each(MARGIN_CASES)('%s reaches useMargin and emits %s', (prop, cssProp) => {
        const a = stateEffectApi({[prop]: '8px'}).marginStyles.value
        const b = stateEffectApi({[prop]: '12px'}).marginStyles.value

        expect(a).toContain(`${cssProp}: 8px`)
        expect(b).toContain(`${cssProp}: 12px`)
        expect(a).not.toEqual(b)
    })
})

describe('useStateEffect forwards every rounded corner', () => {
    it('covers both corner grids', () => {
        // 4 physical corners + 4 logical corners
        expect(ROUNDED_CASES).toHaveLength(8)
    })

    it.each(ROUNDED_CASES)('%s reaches useRounded and emits %s', (prop, cssProp) => {
        const a = stateEffectApi({[prop]: '4px'}).roundedStyles.value
        const b = stateEffectApi({[prop]: '20px'}).roundedStyles.value

        expect(a).toContain(`${cssProp}: 4px`)
        expect(b).toContain(`${cssProp}: 20px`)
        expect(a).not.toEqual(b)
    })
})

// ───────────────────────────────────────────────────────────────────────
// 2. The getter bag must not have been built by VALUE.
//    A plain literal bag (`{ padding: padding.value }`) captures once at
//    call time and the downstream computed never re-runs. The file's own
//    comment says this is why the bags use getters; this pins it for the
//    NEW props specifically, since that is what a future edit would get
//    wrong.
// ───────────────────────────────────────────────────────────────────────

describe('forwarded directionals stay reactive through the getter bag', () => {
    it('a logical-side padding prop recomputes on a value swap', () => {
        const props = reactive<Record<string, unknown>>({paddingInlineStart: '8px'})
        const api = stateEffectApi(props)

        expect(api.paddingStyles.value).toContain('padding-inline-start: 8px')

        props.paddingInlineStart = '40px'

        expect(api.paddingStyles.value).toContain('padding-inline-start: 40px')
        expect(api.paddingStyles.value).not.toContain('padding-inline-start: 8px')
    })

    it('a logical-side margin prop recomputes on a value swap', () => {
        const props = reactive<Record<string, unknown>>({marginBlockEnd: '2px'})
        const api = stateEffectApi(props)

        expect(api.marginStyles.value).toContain('margin-block-end: 2px')

        props.marginBlockEnd = '24px'

        expect(api.marginStyles.value).toContain('margin-block-end: 24px')
    })

    it('a logical corner recomputes on a value swap', () => {
        const props = reactive<Record<string, unknown>>({roundedStartEnd: '4px'})
        const api = stateEffectApi(props)

        expect(api.roundedStyles.value).toContain('border-start-end-radius: 4px')

        props.roundedStartEnd = '16px'

        expect(api.roundedStyles.value).toContain('border-start-end-radius: 16px')
    })
})

// ───────────────────────────────────────────────────────────────────────
// 3. Precedence survives the hop through `useStateEffect`.
//    The bag could forward every key and still break the grammar, because
//    the `padding` / `rounded` SHORTHAND goes through a state-resolved ref
//    while the directionals read the base props. Order is what encodes
//    precedence here (later inline declaration wins), so assert on INDEX.
// ───────────────────────────────────────────────────────────────────────

describe('precedence is preserved across useStateEffect', () => {
    it('padding: physical side > logical side > axis > shorthand', () => {
        const styles = stateEffectApi({
            padding: '2px',
            paddingInline: '10px',
            paddingInlineStart: '50px',
            paddingLeft: '99px'
        }).paddingStyles.value

        const idx = (needle: string) => styles.findIndex(s => s.startsWith(needle))

        expect(idx('padding:')).toBeGreaterThanOrEqual(0)
        expect(idx('padding-inline:')).toBeGreaterThan(idx('padding:'))
        expect(idx('padding-inline-start:')).toBeGreaterThan(idx('padding-inline:'))
        expect(idx('padding-left:')).toBeGreaterThan(idx('padding-inline-start:'))
    })

    it('rounded: physical corner > logical corner > shorthand', () => {
        const styles = stateEffectApi({
            rounded: 'lg',
            roundedStartStart: '7px',
            roundedTopLeft: '0px'
        }).roundedStyles.value

        const idx = (needle: string) => styles.findIndex(s => s.startsWith(needle))

        expect(idx('border-radius:')).toBe(0)
        expect(idx('border-start-start-radius:')).toBeGreaterThan(idx('border-radius:'))
        expect(idx('border-top-left-radius:')).toBeGreaterThan(idx('border-start-start-radius:'))
    })

    it('an untargeted edge keeps cascading from the rung below', () => {
        const styles = stateEffectApi({
            paddingInline: '10px',
            paddingInlineStart: '50px'
        }).paddingStyles.value

        // inline-start is overridden; inline-end still resolves from the
        // axis prop because nothing narrower targets it.
        expect(styles).toContain('padding-inline: 10px')
        expect(styles).toContain('padding-inline-start: 50px')
        expect(styles.some(s => s.startsWith('padding-inline-end:'))).toBe(false)
    })
})

// ───────────────────────────────────────────────────────────────────────
// 4. The hover/active state swap must not clobber a directional.
//    `useStateEffect`'s whole job is swapping the SHORTHAND on hover. The
//    directionals are not state-swappable, so they must survive the swap
//    rather than being dropped with it — a plausible regression if someone
//    later moves the directional reads inside the state-resolution branch.
// ───────────────────────────────────────────────────────────────────────

describe('a directional survives a hover state swap', () => {
    it('keeps padding-inline-start while the shorthand changes on hover', () => {
        const isHover = ref(false)
        const hoverState = computed(() => ({padding: '30px'}))

        let api!: ReturnType<typeof useStateEffect>
        mount(defineComponent({
            name: 'OrigamStateEffectHoverHost',
            setup () {
                api = useStateEffect(
                    reactive({padding: '2px', paddingInlineStart: '50px'}) as never,
                    isHover,
                    undefined,
                    hoverState as never
                )
                return () => h('div')
            }
        }))

        expect(api.paddingStyles.value).toContain('padding: 2px')
        expect(api.paddingStyles.value).toContain('padding-inline-start: 50px')

        isHover.value = true

        // The shorthand took the hover value…
        expect(api.paddingStyles.value).toContain('padding: 30px')
        // …and the directional is still there, still last, still winning.
        expect(api.paddingStyles.value).toContain('padding-inline-start: 50px')
    })
})
